import { useState } from 'react'; import { Alert,Platform,Pressable,SafeAreaView,Text,TextInput,View } from 'react-native'; import * as AppleAuthentication from 'expo-apple-authentication'; import * as Crypto from 'expo-crypto'; import * as Linking from 'expo-linking'; import * as WebBrowser from 'expo-web-browser'; import { mobileSupabase } from '@human/database/mobile'; import { colors,radii,spacing } from '../src/theme';
WebBrowser.maybeCompleteAuthSession();
export default function Auth(){const [signup,setSignup]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false);
async function emailAuth(){setBusy(true);const r=signup?await mobileSupabase.auth.signUp({email,password}):await mobileSupabase.auth.signInWithPassword({email,password});setBusy(false);if(r.error)Alert.alert('Could not continue',r.error.message);else if(signup)Alert.alert('Check your email','Use the verification link to finish creating your account.');}
async function oauth(provider:'google'|'apple'){const redirectTo=Linking.createURL('/auth');const {data,error}=await mobileSupabase.auth.signInWithOAuth({provider,options:{redirectTo,skipBrowserRedirect:true}});if(error||!data.url){Alert.alert('Could not continue',error?.message??'Missing authorization URL.');return;}const result=await WebBrowser.openAuthSessionAsync(data.url,redirectTo);if(result.type==='success'){const parsed=Linking.parse(result.url);const code=String(parsed.queryParams?.code??'');if(code)await mobileSupabase.auth.exchangeCodeForSession(code);}}
async function nativeApple(){try{const rawNonce=Crypto.randomUUID();const credential=await AppleAuthentication.signInAsync({requestedScopes:[AppleAuthentication.AppleAuthenticationScope.FULL_NAME,AppleAuthentication.AppleAuthenticationScope.EMAIL],nonce:rawNonce});if(!credential.identityToken)throw new Error('Apple did not return an identity token.');const {error}=await mobileSupabase.auth.signInWithIdToken({provider:'apple',token:credential.identityToken,nonce:rawNonce});if(error)throw error;}catch(e:any){if(e.code!=='ERR_REQUEST_CANCELED')Alert.alert('Apple sign-in failed',e.message);}}
return <SafeAreaView style={{flex:1,backgroundColor:colors.background}}><View style={{padding:spacing.lg,flex:1,justifyContent:'center',gap:spacing.md}}><Text style={{fontSize:52,fontWeight:'800',letterSpacing:-2,color:colors.text}}>Real inspiration exists.</Text><Text style={{fontSize:18,lineHeight:26,color:colors.textSecondary}}>Discover work made by people—and see the proof behind it.</Text>
<TextInput value={email} onChangeText={setEmail} placeholder="Email" autoCapitalize="none" keyboardType="email-address" style={{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radii.control,padding:15}}/><TextInput value={password} onChangeText={setPassword} placeholder="Password" secureTextEntry style={{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:radii.control,padding:15}}/>
<Pressable disabled={busy} onPress={emailAuth} style={{backgroundColor:colors.accent,padding:16,borderRadius:radii.control,alignItems:'center'}}><Text style={{color:'white',fontWeight:'800'}}>{busy?'Please wait…':signup?'Create account':'Sign in'}</Text></Pressable>
{Platform.OS==='ios'&&<AppleAuthentication.AppleAuthenticationButton buttonType={AppleAuthentication.AppleAuthenticationButtonType.CONTINUE} buttonStyle={AppleAuthentication.AppleAuthenticationButtonStyle.BLACK} cornerRadius={10} style={{height:50}} onPress={nativeApple}/>}<Pressable onPress={()=>oauth('google')} style={{backgroundColor:colors.surface,padding:16,borderWidth:1,borderColor:colors.border,borderRadius:radii.control,alignItems:'center'}}><Text style={{fontWeight:'700'}}>Continue with Google</Text></Pressable>
<Pressable onPress={()=>setSignup(!signup)}><Text style={{textAlign:'center',color:colors.accent,fontWeight:'700'}}>{signup?'Already have an account? Sign in':'New here? Create an account'}</Text></Pressable></View></SafeAreaView>}
