import { createHash, randomBytes, randomUUID } from 'node:crypto';
import sharp from 'sharp';
import { createClient } from '@supabase/supabase-js';

type Sample = {
  key: 'clean_camera' | 'known_ai' | 'screen_recapture';
  label: string;
  sourceUrl: string;
  sourceNote: string;
  expected: string;
};

type StoredDetectorRow = {
  provider: string;
  provider_role: string;
  status: string;
  model_version: string | null;
  ai_score: number | null;
  authentic_score: number | null;
  confidence: number | null;
  recapture_score: number | null;
  deepfake_score: number | null;
  partial_ai_score: number | null;
  content_flags: Record<string, unknown> | null;
  raw_response: Record<string, unknown> | null;
  error_code: string | null;
  latency_ms: number | null;
};

const samples: Sample[] = [
  {
    key: 'clean_camera',
    label: 'Clean genuine iPhone camera photo',
    sourceUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Landscape%20photo.JPG',
    sourceNote: 'Wikimedia Commons original JPEG photographed with an Apple iPhone 4S and carrying camera EXIF.',
    expected: 'VERIFIED or ESCALATE; must not reject.',
  },
  {
    key: 'known_ai',
    label: 'Known DALL-E 3 generated image',
    sourceUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/DALL-E%203%20example%20AI%20generated%20image.png',
    sourceNote: 'Wikimedia Commons file explicitly labelled as generated by OpenAI DALL-E 3.',
    expected: 'REJECTED or ESCALATE; must not verify.',
  },
  {
    key: 'screen_recapture',
    label: 'Camera photograph of a Midjourney screen',
    sourceUrl: 'https://unsplash.com/photos/hpz88a0NUS8/download?force=true&w=1600',
    sourceNote: 'Actual Sony-camera photograph of a computer display showing the Midjourney interface/generated-image workflow; used as the closest openly licensed real screen-recapture sample.',
    expected: 'ESCALATE acceptable; VERIFIED must be flagged loudly.',
  },
];

function env(name: string, fallbacks: string[] = []): string {
  for (const candidate of [name, ...fallbacks]) {
    const value = process.env[candidate]?.trim();
    if (value) return value;
  }
  throw new Error(`Missing required smoke-test environment variable: ${name}`);
}

function sha256(bytes: Buffer): string {
  return createHash('sha256').update(bytes).digest('hex');
}

function ratio(width: number, height: number): string {
  function gcd(a: number, b: number): number {
    let left = Math.abs(a);
    let right = Math.abs(b);
    while (right) [left, right] = [right, left % right];
    return left || 1;
  }
  const divisor = gcd(width, height);
  return `${Math.round(width / divisor)}:${Math.round(height / divisor)}`;
}

function jsonRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === 'object' && !Array.isArray(value)
    ? value as Record<string, unknown>
    : {};
}

function numberValue(value: unknown): number | null {
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  if (typeof value === 'string' && value.trim() && Number.isFinite(Number(value))) return Number(value);
  return null;
}

function findClassValue(value: unknown, target: string): number | null {
  if (Array.isArray(value)) {
    for (const child of value) {
      const found = findClassValue(child, target);
      if (found !== null) return found;
    }
    return null;
  }
  if (!value || typeof value !== 'object') return null;
  const row = value as Record<string, unknown>;
  const name = typeof row.class === 'string'
    ? row.class
    : typeof row.class_name === 'string'
      ? row.class_name
      : typeof row.label === 'string'
        ? row.label
        : null;
  const score = numberValue(row.value ?? row.score ?? row.confidence ?? row.probability);
  if (name?.trim().toLowerCase() === target && score !== null) return score;
  for (const child of Object.values(row)) {
    const found = findClassValue(child, target);
    if (found !== null) return found;
  }
  return null;
}

function nestedNumber(root: unknown, paths: string[][]): number | null {
  for (const path of paths) {
    let cursor: unknown = root;
    for (const key of path) {
      if (!cursor || typeof cursor !== 'object' || Array.isArray(cursor)) {
        cursor = undefined;
        break;
      }
      cursor = (cursor as Record<string, unknown>)[key];
    }
    const value = numberValue(cursor);
    if (value !== null) return value;
  }
  return null;
}

function rawScoreSummary(row: StoredDetectorRow) {
  const raw = jsonRecord(row.raw_response);
  if (row.provider === 'sightengine') {
    const core = jsonRecord(raw.core);
    return {
      aiGenerated: nestedNumber(core, [
        ['type', 'ai_generated'],
        ['type', 'ai_generated_probability'],
        ['ai_generated'],
      ]),
      deepfake: nestedNumber(core, [
        ['deepfake', 'score'],
        ['deepfake', 'probability'],
        ['type', 'deepfake'],
      ]),
      recapture: nestedNumber(raw.recapture, [
        ['recapture', 'score'],
        ['recapture', 'probability'],
        ['type', 'recapture'],
      ]),
      providerStatus: core.status ?? null,
      recaptureStatus: row.content_flags?.recapture_status ?? null,
    };
  }
  if (row.provider === 'hive') {
    return {
      aiGenerated: findClassValue(raw, 'ai_generated'),
      notAiGenerated: findClassValue(raw, 'not_ai_generated'),
      deepfake: findClassValue(raw, 'deepfake'),
    };
  }
  return {};
}

async function fetchImage(sample: Sample): Promise<{ bytes: Buffer; mimeType: string; extension: string }> {
  const response = await fetch(sample.sourceUrl, {
    redirect: 'follow',
    cache: 'no-store',
    headers: { 'user-agent': 'Humn verification smoke test/1.0' },
    signal: AbortSignal.timeout(30_000),
  });
  if (!response.ok) throw new Error(`${sample.key} source returned HTTP ${response.status}`);
  const bytes = Buffer.from(await response.arrayBuffer());
  if (bytes.length <= 0 || bytes.length > 15 * 1024 * 1024) {
    throw new Error(`${sample.key} source size ${bytes.length} is outside the accepted range`);
  }
  const metadata = await sharp(bytes, { failOn: 'error', limitInputPixels: 100_000_000 }).metadata();
  const format = metadata.format;
  if (!format || !['jpeg', 'png', 'webp'].includes(format)) {
    throw new Error(`${sample.key} source format ${format ?? 'unknown'} is unsupported`);
  }
  return {
    bytes,
    mimeType: format === 'jpeg' ? 'image/jpeg' : `image/${format}`,
    extension: format === 'jpeg' ? 'jpg' : format,
  };
}

async function main() {
  if (process.env.VERCEL_ENV !== 'preview' || process.env.VERCEL_GIT_COMMIT_REF !== 'feat/automated-verification-pipeline') {
    console.log('HUMN_VERIFICATION_SMOKE_SKIP', JSON.stringify({
      reason: 'not_the_target_preview',
      vercelEnv: process.env.VERCEL_ENV ?? null,
      branch: process.env.VERCEL_GIT_COMMIT_REF ?? null,
    }));
    return;
  }

  // The smoke test intentionally validates the free-plan configuration. Missing
  // vendor recapture remains an explicit escalation signal, never a silent clear.
  process.env.SIGHTENGINE_RECAPTURE_ENABLED = 'false';

  const supabaseUrl = env('NEXT_PUBLIC_SUPABASE_URL');
  const adminKey = env('SUPABASE_SECRET_KEY', ['SUPABASE_SERVICE_ROLE_KEY']);
  const publicKey = env('NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY', ['NEXT_PUBLIC_SUPABASE_ANON_KEY']);
  env('SIGHTENGINE_API_USER');
  env('SIGHTENGINE_API_SECRET');
  env('HIVE_V3_SECRET_KEY', ['HIVE_API_KEY']);
  env('AUTOMATED_REVIEW_SECRET');

  const admin = createClient(supabaseUrl, adminKey, {
    auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false },
  });

  const readiness = await admin.rpc('claim_verification_run', {
    p_work_id: '00000000-0000-0000-0000-000000000000',
  });
  if (readiness.error) {
    throw new Error(`Verification database migrations are not ready: ${readiness.error.code ?? 'unknown'} ${readiness.error.message}`);
  }

  const smokeKey = (process.env.VERCEL_GIT_COMMIT_SHA ?? randomUUID()).slice(0, 12).toLowerCase();
  const email = `verification-smoke-${smokeKey}@example.invalid`;
  const password = `${randomBytes(32).toString('base64url')}Aa1!`;
  const handle = `smoke_${smokeKey.replace(/[^a-z0-9]/g, '').slice(0, 18)}`;

  const created = await admin.auth.admin.createUser({
    email,
    password,
    email_confirm: true,
    user_metadata: {
      requested_handle: handle,
      display_name: 'Humn Verification Smoke Test',
    },
  });
  if (created.error || !created.data.user) {
    throw new Error(`Smoke user creation failed: ${created.error?.message ?? 'missing user'}`);
  }
  const userId = created.data.user.id;

  const userClient = createClient(supabaseUrl, publicKey, {
    auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false },
  });
  const signIn = await userClient.auth.signInWithPassword({ email, password });
  if (signIn.error || !signIn.data.user) {
    throw new Error(`Smoke user sign-in failed: ${signIn.error?.message ?? 'missing session'}`);
  }

  const profile = await admin.from('users').select('id, handle').eq('id', userId).maybeSingle();
  if (profile.error) throw new Error(`Smoke profile lookup failed: ${profile.error.message}`);
  if (!profile.data) throw new Error('Smoke auth trigger did not create a public creator profile.');

  const profileCompletion = await userClient.rpc('complete_humn_profile', {
    p_handle: handle,
    p_display_name: 'Humn Verification Smoke Test',
  });
  if (profileCompletion.error) {
    const normalized = profileCompletion.error.message.toLowerCase();
    if (!normalized.includes('handle_change_not_allowed')) {
      throw new Error(`Smoke profile completion failed: ${profileCompletion.error.message}`);
    }
  }

  const { runVerificationForWork } = await import('../lib/verification/pipeline');
  const reports: Record<string, unknown>[] = [];
  const workIds: string[] = [];

  for (const sample of samples) {
    const source = await fetchImage(sample);
    const metadata = await sharp(source.bytes, { failOn: 'error', limitInputPixels: 100_000_000 }).metadata();
    if (!metadata.width || !metadata.height) throw new Error(`${sample.key} dimensions are missing`);

    const workId = randomUUID();
    workIds.push(workId);
    const originalPath = `${userId}/${workId}/original.${source.extension}`;
    const displayPath = `${userId}/${workId}/display.webp`;
    const thumbPath = `${userId}/${workId}/thumbnail.webp`;
    const display = await sharp(source.bytes).autoOrient().resize({ width: 1600, height: 1600, fit: 'inside', withoutEnlargement: true }).webp({ quality: 88 }).toBuffer();
    const thumb = await sharp(source.bytes).autoOrient().resize({ width: 640, height: 640, fit: 'inside', withoutEnlargement: true }).webp({ quality: 80 }).toBuffer();

    const originalUpload = await admin.storage.from('work-originals').upload(originalPath, source.bytes, {
      contentType: source.mimeType,
      cacheControl: '31536000',
      upsert: false,
    });
    if (originalUpload.error) throw new Error(`${sample.key} original upload failed: ${originalUpload.error.message}`);
    const displayUpload = await admin.storage.from('work-display').upload(displayPath, display, {
      contentType: 'image/webp', cacheControl: '31536000', upsert: false,
    });
    if (displayUpload.error) throw new Error(`${sample.key} display upload failed: ${displayUpload.error.message}`);
    const thumbUpload = await admin.storage.from('work-display').upload(thumbPath, thumb, {
      contentType: 'image/webp', cacheControl: '31536000', upsert: false,
    });
    if (thumbUpload.error) throw new Error(`${sample.key} thumbnail upload failed: ${thumbUpload.error.message}`);

    const imageUrl = admin.storage.from('work-display').getPublicUrl(displayPath).data.publicUrl;
    const thumbUrl = admin.storage.from('work-display').getPublicUrl(thumbPath).data.publicUrl;
    const originalHash = sha256(source.bytes);
    const signals = [
      {
        signal_name: 'c2pa',
        value: {
          state: 'none',
          embedded: false,
          camera_capture_asserted: false,
          ai_generation_asserted: false,
          validation_status: [],
          note: 'Smoke-test source label is external to the detector decision.',
        },
        weight: 0,
      },
      {
        signal_name: 'exif_consistency',
        value: {
          state: 'smoke_test_source',
          present: false,
          plausible_field_count: 0,
          note: 'The smoke test isolates live content-detector behavior; this neutral field is not used as an AI verdict.',
        },
        weight: 0,
      },
      {
        signal_name: 'origin_input',
        value: {
          origin_input: 'uploaded',
          note: 'Server-side verification smoke-test fixture.',
        },
        weight: 0,
      },
    ];

    const workInsert = await admin.rpc('create_origin_work_with_provenance', {
      p_work_id: workId,
      p_creator_id: userId,
      p_title: `__HUMN_SMOKE__:${smokeKey}:${sample.key}`,
      p_description: `${sample.label}. ${sample.sourceNote}`,
      p_category: 'photography',
      p_aspect_ratio: ratio(metadata.width, metadata.height),
      p_image_url: imageUrl,
      p_thumb_url: thumbUrl,
      p_origin_input: 'uploaded',
      p_capture_device: null,
      p_lens: null,
      p_iso: null,
      p_shutter: null,
      p_dimensions: `${metadata.width} × ${metadata.height} px`,
      p_file_format: (metadata.format ?? source.extension).toUpperCase(),
      p_original_hash: originalHash,
      p_captured_at: null,
      p_uploaded_at: new Date().toISOString(),
      p_signals: signals,
      p_ai_declared: false,
    });
    if (workInsert.error) {
      throw new Error(`${sample.key} Work creation failed: ${workInsert.error.code ?? 'unknown'} ${workInsert.error.message}`);
    }

    const proofInsert = await admin.from('proof_entries').insert({
      id: randomUUID(),
      work_id: workId,
      seq: 1,
      captured_at: new Date().toISOString(),
      title: 'Smoke-test process evidence',
      body: `Labelled verification smoke-test input: ${sample.sourceNote}`,
      thumb_url: null,
    });
    if (proofInsert.error) throw new Error(`${sample.key} proof creation failed: ${proofInsert.error.message}`);

    const request = await userClient.rpc('request_work_verification', { p_work_id: workId });
    if (request.error) {
      throw new Error(`${sample.key} authenticated verification request failed: ${request.error.code ?? 'unknown'} ${request.error.message}`);
    }

    const workerOutcome = await runVerificationForWork(workId);
    if (!workerOutcome.processed || !workerOutcome.runId) {
      throw new Error(`${sample.key} worker did not claim the queued verification run`);
    }

    const [workRow, runRow, detectorRows, auditRows] = await Promise.all([
      admin.from('works').select('id, status, review_note, removed_at').eq('id', workId).single(),
      admin.from('verification_pipeline_runs').select('*').eq('id', workerOutcome.runId).single(),
      admin.from('verification_detector_results').select('*').eq('run_id', workerOutcome.runId).order('provider_role'),
      admin.from('verification_audit_events').select('event_type, actor_type, metadata, created_at').eq('run_id', workerOutcome.runId).order('created_at'),
    ]);
    if (workRow.error) throw new Error(`${sample.key} final Work read failed: ${workRow.error.message}`);
    if (runRow.error) throw new Error(`${sample.key} run read failed: ${runRow.error.message}`);
    if (detectorRows.error) throw new Error(`${sample.key} detector read failed: ${detectorRows.error.message}`);
    if (auditRows.error) throw new Error(`${sample.key} audit read failed: ${auditRows.error.message}`);

    const normalizedDetectors = (detectorRows.data as StoredDetectorRow[]).map(row => ({
      provider: row.provider,
      role: row.provider_role,
      status: row.status,
      modelVersion: row.model_version,
      normalized: {
        aiScore: row.ai_score,
        authenticScore: row.authentic_score,
        confidence: row.confidence,
        deepfakeScore: row.deepfake_score,
        recaptureScore: row.recapture_score,
      },
      rawScoreFields: rawScoreSummary(row),
      contentFlags: row.content_flags,
      errorCode: row.error_code,
      latencyMs: row.latency_ms,
      rawResponseStored: Boolean(row.raw_response && Object.keys(row.raw_response).length > 0),
    }));

    reports.push({
      sample: sample.key,
      label: sample.label,
      sourceNote: sample.sourceNote,
      expected: sample.expected,
      workId,
      runId: workerOutcome.runId,
      finalWorkState: workRow.data.status,
      decision: runRow.data.decision,
      reasonCode: runRow.data.reason_code,
      reason: runRow.data.reason,
      thresholds: runRow.data.thresholds,
      screenHeuristics: runRow.data.screen_heuristics,
      evidenceDigest: runRow.data.evidence_digest,
      detectors: normalizedDetectors,
      audit: auditRows.data,
    });
  }

  await admin.from('works').update({ removed_at: new Date().toISOString() }).in('id', workIds);
  await admin.auth.admin.updateUserById(userId, { ban_duration: '876000h' });

  console.log('HUMN_VERIFICATION_SMOKE_RESULT', JSON.stringify({
    ok: true,
    smokeKey,
    preview: {
      commit: process.env.VERCEL_GIT_COMMIT_SHA ?? null,
      branch: process.env.VERCEL_GIT_COMMIT_REF ?? null,
      recaptureEnabled: false,
      readiness: [
        'Sightengine AI score',
        'Sightengine confidence',
        'Sightengine deepfake score',
        'Hive AI score',
        'Hive confidence',
        'Hive deepfake score',
      ],
    },
    reports,
    note: 'Three-sample wiring smoke test only. Precision, recall and false-positive rate remain unmeasured.',
  }));
}

main().catch(error => {
  console.error('HUMN_VERIFICATION_SMOKE_RESULT', JSON.stringify({
    ok: false,
    errorClass: error instanceof Error ? error.name : 'UnknownError',
    error: error instanceof Error ? error.message : String(error),
    note: 'The preview deployment is not failed by this one-time smoke harness; inspect this result before proceeding.',
  }));
});
