create or replace function public.role_for(uid uuid) returns public.user_role language sql stable security definer set search_path='' as $$ select role from public.profiles where id=uid $$;
create or replace function public.is_staff(uid uuid) returns boolean language sql stable security definer set search_path='' as $$ select coalesce(public.role_for(uid) in ('support','moderator','senior_moderator','trust_safety_lead','admin','auditor'),false) $$;
create or replace function public.can_decide_cases(uid uuid) returns boolean language sql stable security definer set search_path='' as $$ select coalesce(public.role_for(uid) in ('moderator','senior_moderator','trust_safety_lead','admin'),false) $$;
create or replace function public.can_review_evidence(uid uuid) returns boolean language sql stable security definer set search_path='' as $$ select coalesce(public.role_for(uid) in ('moderator','senior_moderator','trust_safety_lead','admin','auditor'),false) $$;
create or replace function public.can_access_collection(cid uuid,uid uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.collections c where c.id=cid and (c.owner_id=uid or c.privacy='public' or exists(select 1 from public.collection_collaborators cc where cc.collection_id=c.id and cc.user_id=uid and cc.accepted_at is not null))) $$;
create or replace function public.can_edit_collection(cid uuid,uid uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.collections c where c.id=cid and (c.owner_id=uid or exists(select 1 from public.collection_collaborators cc where cc.collection_id=c.id and cc.user_id=uid and cc.accepted_at is not null and cc.role in ('owner','editor')))) $$;

alter table public.profiles enable row level security; alter table public.user_settings enable row level security; alter table public.user_interests enable row level security; alter table public.creator_profiles enable row level security; alter table public.creator_categories enable row level security; alter table public.categories enable row level security; alter table public.works enable row level security; alter table public.work_media enable row level security; alter table public.work_origin_declarations enable row level security; alter table public.proof_stories enable row level security; alter table public.proof_story_items enable row level security; alter table public.collections enable row level security; alter table public.collection_sections enable row level security; alter table public.collection_items enable row level security; alter table public.collection_collaborators enable row level security; alter table public.follows enable row level security; alter table public.work_saves enable row level security; alter table public.reports enable row level security; alter table public.moderation_cases enable row level security; alter table public.moderation_actions enable row level security; alter table public.notification_preferences enable row level security; alter table public.subscriptions enable row level security; alter table public.entitlements enable row level security; alter table public.recommendation_events enable row level security; alter table public.feed_impressions enable row level security; alter table public.feed_actions enable row level security; alter table public.visual_embeddings enable row level security; alter table public.feature_flags enable row level security; alter table public.device_sessions enable row level security; alter table public.security_events enable row level security; alter table public.audit_logs enable row level security; alter table public.deletion_requests enable row level security;

create policy profiles_public_read on public.profiles for select using(deleted_at is null);
create policy profiles_self_update on public.profiles for update using(auth.uid()=id) with check(auth.uid()=id and role=public.role_for(auth.uid()));
create policy settings_self_all on public.user_settings for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy interests_self_all on public.user_interests for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy categories_public_read on public.categories for select using(is_active);
create policy creators_public_read on public.creator_profiles for select using(true); create policy creators_self_write on public.creator_profiles for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy creator_categories_public_read on public.creator_categories for select using(true); create policy creator_categories_self_write on public.creator_categories for all using(auth.uid()=creator_id) with check(auth.uid()=creator_id);
create policy works_public_read on public.works for select using((status='published' and deleted_at is null) or creator_id=auth.uid() or public.can_review_evidence(auth.uid()));
create policy works_owner_insert on public.works for insert with check(creator_id=auth.uid()); create policy works_owner_update on public.works for update using(creator_id=auth.uid()) with check(creator_id=auth.uid()); create policy works_owner_delete on public.works for delete using(creator_id=auth.uid());
create policy work_media_read on public.work_media for select using(exists(select 1 from public.works w where w.id=work_id and (w.status='published' or w.creator_id=auth.uid() or public.can_review_evidence(auth.uid()))));
create policy work_media_owner_write on public.work_media for all using(exists(select 1 from public.works w where w.id=work_id and w.creator_id=auth.uid())) with check(exists(select 1 from public.works w where w.id=work_id and w.creator_id=auth.uid()));
create policy declarations_owner_staff_read on public.work_origin_declarations for select using(creator_id=auth.uid() or public.can_review_evidence(auth.uid())); create policy declarations_owner_write on public.work_origin_declarations for all using(creator_id=auth.uid()) with check(creator_id=auth.uid());
create policy proof_read on public.proof_stories for select using(is_public or creator_id=auth.uid() or public.can_review_evidence(auth.uid())); create policy proof_owner_write on public.proof_stories for all using(creator_id=auth.uid()) with check(creator_id=auth.uid());
create policy proof_items_read on public.proof_story_items for select using(exists(select 1 from public.proof_stories p where p.id=proof_story_id and (p.is_public or p.creator_id=auth.uid() or public.can_review_evidence(auth.uid()))));
create policy proof_items_write on public.proof_story_items for all using(exists(select 1 from public.proof_stories p where p.id=proof_story_id and p.creator_id=auth.uid())) with check(exists(select 1 from public.proof_stories p where p.id=proof_story_id and p.creator_id=auth.uid()));
create policy collections_read on public.collections for select using(public.can_access_collection(id,auth.uid())); create policy collections_owner_write on public.collections for all using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy sections_read on public.collection_sections for select using(public.can_access_collection(collection_id,auth.uid())); create policy sections_write on public.collection_sections for all using(public.can_edit_collection(collection_id,auth.uid())) with check(public.can_edit_collection(collection_id,auth.uid()));
create policy collection_items_read on public.collection_items for select using(public.can_access_collection(collection_id,auth.uid())); create policy collection_items_write on public.collection_items for all using(public.can_edit_collection(collection_id,auth.uid())) with check(public.can_edit_collection(collection_id,auth.uid()) and added_by=auth.uid());
create policy collaborators_read on public.collection_collaborators for select using(public.can_access_collection(collection_id,auth.uid())); create policy collaborators_owner_write on public.collection_collaborators for all using(exists(select 1 from public.collections c where c.id=collection_id and c.owner_id=auth.uid())) with check(exists(select 1 from public.collections c where c.id=collection_id and c.owner_id=auth.uid()));
create policy follows_public_read on public.follows for select using(true); create policy follows_self_write on public.follows for all using(follower_id=auth.uid()) with check(follower_id=auth.uid());
create policy saves_self_all on public.work_saves for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy reports_insert on public.reports for insert with check(reporter_id=auth.uid()); create policy reports_self_staff_read on public.reports for select using(reporter_id=auth.uid() or public.is_staff(auth.uid()));
create policy moderation_staff_read on public.moderation_cases for select using(public.is_staff(auth.uid())); create policy moderation_reviewer_insert on public.moderation_cases for insert with check(public.can_decide_cases(auth.uid())); create policy moderation_reviewer_update on public.moderation_cases for update using(public.can_decide_cases(auth.uid())) with check(public.can_decide_cases(auth.uid())); create policy moderation_actions_staff_read on public.moderation_actions for select using(public.is_staff(auth.uid())); create policy moderation_actions_reviewer_insert on public.moderation_actions for insert with check(public.can_decide_cases(auth.uid()) and actor_id=auth.uid());
create policy notification_self_all on public.notification_preferences for all using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy subscriptions_self_read on public.subscriptions for select using(user_id=auth.uid()); create policy entitlements_self_read on public.entitlements for select using(user_id=auth.uid());
create policy recommendation_insert on public.recommendation_events for insert with check(user_id is null or user_id=auth.uid()); create policy impressions_insert on public.feed_impressions for insert with check(user_id is null or user_id=auth.uid()); create policy actions_insert on public.feed_actions for insert with check(exists(select 1 from public.feed_impressions i where i.id=impression_id and i.user_id=auth.uid()));
create policy feature_flags_read on public.feature_flags for select using(true); create policy devices_self_all on public.device_sessions for all using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy deletion_self_all on public.deletion_requests for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy security_staff_read on public.security_events for select using(public.is_staff(auth.uid())); create policy audit_staff_read on public.audit_logs for select using(public.is_staff(auth.uid()));

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values
('public-work-media','public-work-media',true,52428800,array['image/jpeg','image/png','image/webp','video/mp4']),
('private-original-files','private-original-files',false,209715200,null),
('private-proof-evidence','private-proof-evidence',false,209715200,null),
('profile-media','profile-media',true,10485760,array['image/jpeg','image/png','image/webp']),
('collection-covers','collection-covers',true,10485760,array['image/jpeg','image/png','image/webp']),
('temporary-uploads','temporary-uploads',false,209715200,null)
on conflict(id) do nothing;

create policy public_media_read on storage.objects for select using(bucket_id in ('public-work-media','profile-media','collection-covers'));
create policy user_upload_own_folder on storage.objects for insert to authenticated with check(bucket_id in ('profile-media','collection-covers') and (storage.foldername(name))[1]=auth.uid()::text);
create policy user_update_own_folder on storage.objects for update to authenticated using(bucket_id in ('profile-media','collection-covers') and (storage.foldername(name))[1]=auth.uid()::text) with check(bucket_id in ('profile-media','collection-covers') and (storage.foldername(name))[1]=auth.uid()::text);
create policy private_owner_staff_read on storage.objects for select to authenticated using(bucket_id in ('private-original-files','private-proof-evidence','temporary-uploads') and ((storage.foldername(name))[1]=auth.uid()::text or public.can_review_evidence(auth.uid())));
